<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>TopSocket</AssemblyName>
    <BepInExPluginGuid>moe.milkydelta.PEAK.TopSocket</BepInExPluginGuid>
    <Product>HTTP/WS Status</Product>
    <Version>0.2.0</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <RestoreAdditionalProjectSources>
      https://api.nuget.org/v3/index.json;
      https://nuget.bepinex.dev/v3/index.json;
      https://nuget.samboy.dev/v3/index.json
    </RestoreAdditionalProjectSources>
    <RootNamespace>TopSocket</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <SteamAppsCommon>/mnt/solidus/SteamLibrary/steamapps/common</SteamAppsCommon>
    <GameDataDirectory>$(SteamAppsCommon)/PEAK/PEAK_Data</GameDataDirectory>
  </PropertyGroup>

  <PropertyGroup>
    <PluginCopyTargetDir Condition="$(Configuration)==Debug">$(SteamAppsCommon)/PEAK/BepInEx/plugins</PluginCopyTargetDir>
    <PluginCopyTargetDir Condition="$(Configuration)!=Debug">
      bin/$(Configuration)/$(TargetFramework)/BepInEx/plugins</PluginCopyTargetDir>
  </PropertyGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(PluginCopyTargetDir)" />
    <Copy SourceFiles="$(PkgWebSocketSharp)/lib/websocket-sharp.dll"
      DestinationFolder="$(PluginCopyTargetDir)" />

    <!-- Not sure how I'm going to license this. If the license needs to be distributed alongside
    binaries, name it "LICENSE.ProjectName". Otherwise, drop the extension.-->
    <Copy SourceFiles="LICENSE.$(AssemblyName)"
      DestinationFiles="$(PluginCopyTargetDir)/LICENSE.$(AssemblyName).txt"
      Condition="Exists('LICENSE.$(AssemblyName)')" />

    <!-- No WebSocketSharp code is included in this repo, but builds will copy the DLL. If you
    distribute that DLL, you should include the license (MIT).-->
    <Copy SourceFiles="LICENSE.WebSocketSharp"
      DestinationFiles="$(PluginCopyTargetDir)/LICENSE.WebSocketSharp.txt"
      Condition="Exists('LICENSE.WebSocketSharp')" />
  </Target>

  <ItemGroup>
    <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
    <PackageReference Include="BepInEx.Core" Version="5.*" />
    <PackageReference Include="BepInEx.PluginInfoProps" Version="2.*" />
    <PackageReference Include="WebSocketSharp" Version="1.0.3-rc11" GeneratePathProperty="true" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(GameDataDirectory)\Managed\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(GameDataDirectory)\Managed\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(GameDataDirectory)\Managed\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(GameDataDirectory)\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="PhotonUnityNetworking">
      <HintPath>$(GameDataDirectory)\Managed\PhotonUnityNetworking.dll</HintPath>
    </Reference>
    <Reference Include="PhotonRealtime">
      <HintPath>$(GameDataDirectory)\Managed\PhotonRealtime.dll</HintPath>
    </Reference>
    <Reference Include="Zorro.Core.Runtime">
      <HintPath>$(GameDataDirectory)\Managed\Zorro.Core.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Sirenix.Serialization">
      <HintPath>$(GameDataDirectory)\Managed\Sirenix.Serialization.dll</HintPath>
    </Reference>

  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2"
      PrivateAssets="all" />
  </ItemGroup>
</Project>