<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>TopSocket</AssemblyName>
    <BepInExPluginGuid>moe.milkydelta.PEAK.TopSocket</BepInExPluginGuid>
    <Product>HTTP/WS Status</Product>
    <Version>0.0.1</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <RestoreAdditionalProjectSources>
      https://api.nuget.org/v3/index.json;
      https://nuget.bepinex.dev/v3/index.json;
      https://nuget.samboy.dev/v3/index.json
    </RestoreAdditionalProjectSources>
    <RootNamespace>TopSocket</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <SteamAppsCommon>/mnt/solidus/SteamLibrary/steamapps/common</SteamAppsCommon>
    <GameDataDirectory>$(SteamAppsCommon)/PEAK/PEAK_Data</GameDataDirectory>
  </PropertyGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(SteamAppsCommon)/PEAK/BepInEx/plugins" />
  </Target>

  <ItemGroup>
    <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
    <PackageReference Include="BepInEx.Core" Version="5.*" />
    <PackageReference Include="BepInEx.PluginInfoProps" Version="2.*" />
    <PackageReference Include="WebSocketSharp" Version="1.0.3-rc11" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(GameDataDirectory)\Managed\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(GameDataDirectory)\Managed\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(GameDataDirectory)\Managed\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(GameDataDirectory)\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="PhotonUnityNetworking">
      <HintPath>$(GameDataDirectory)\Managed\PhotonUnityNetworking.dll</HintPath>
    </Reference>
    <Reference Include="PhotonRealtime">
      <HintPath>$(GameDataDirectory)\Managed\PhotonRealtime.dll</HintPath>
    </Reference>
  </ItemGroup>
  
  <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all" />
  </ItemGroup>
</Project>
